Task A
vladikabr/Structures pull request #5
Opened 2019-06-05 07:49 UTC by vladikabr

2019-06-17 10:02 UTC, sartuhin requested changes

2019-06-17 10:02 UTC, sartuhin commented on AVL Tree/Set.h
> +        int height;
size_t?

2019-06-17 10:02 UTC, sartuhin commented on AVL Tree/Set.h
> +                it = nullptr;
Лучше везде оборачивать однострочный if в {}

2019-06-17 10:02 UTC, sartuhin commented on AVL Tree/Set.h
> +    std::size_t sz;
Зачем так сокращать название переменных?

2019-06-17 10:02 UTC, sartuhin commented on AVL Tree/Set.h
> +        while (p != nullptr && p->key < k) {
P - не говорящее название.

2019-06-17 10:02 UTC, sartuhin commented on AVL Tree/Set.h
> +        while (p != nullptr && p->key < k) {
В остальных местах также.

2019-06-17 12:19 UTC, vladikabr reviewed
случайно написал этот комент, не знаю как удалить)

2019-06-23 06:46 UTC, sartuhin approved these changes

2019-06-23 06:47 UTC, merged